name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Clone stalkerware-indicators repo
      run: git clone --depth=1 https://github.com/Te-k/stalkerware-indicators
    - name: Test load ioc.yaml
      run: cargo run -- stream --rules stalkerware-indicators/ioc.yaml < /dev/null
